server:
  port: 9880
  servlet:
    context-path: /iot
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
      enabled: true

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: org.apache.iotdb.jdbc.IoTDBDriver
      url: jdbc:iotdb://${IOTDB_HOST_DEV}:6667/
      username: ${IOTDB_USERNAME_DEV}
      password: ${IOTDB_PASSWORD_DEV}
      initial-size: 5
      max-active: 20
      min-idle: 1
      max-wait: 60000
      remove-abandoned: true
      remove-abandoned-timeout: 30
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: false
      test-on-borrow: false
      test-on-return: false

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl